세션 기반 인증 추가
giwankim/web-application-server pull request #9
Opened 2024-03-23 03:21 UTC by giwankim

- 전역에서 서버와 형성된 HttpSession관리를 담당하는 HttpSessions 클래스 추가
- HttpSession 클래스 추가
- RequestHandler에서는 세션 쿠키가 없으면 새로 생성한다.
- LoginController에서 사용자가 로그인에 성공하면 User객체를 세션에 추가한다.
- ListUserController는 인증된 User가 세션에 포함되어 있어야만 User 목록을 보여준다.

2024-03-23 11:32 UTC, f-lab-scott requested changes
몇 가지 의견 남깁니다~

2024-03-23 11:32 UTC, f-lab-scott commented on src/main/java/com/giwankim/http/HttpCookies.java
> +  HttpCookies(Map<String, String> cookies) {
요 클래스 작성하시면서 혹시 `Set-Cookie` 의 작동 원리도 조금 학습하셨을까요? 만약 아니라면 [요 페이지](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) 도 참고해 주세요.

2024-03-23 11:32 UTC, f-lab-scott commented on src/main/java/com/giwankim/http/HttpSession.java
> +  private final String id;
요 `id` 는 어떤 원리로 부여되는 것이 좋을까요?
Tomcat 기반 Spring MVC app에선 이 ID가 어떻게 부여되고 있을까요? 추가 학습해 보시면 좋겠습니다.

2024-03-23 11:32 UTC, f-lab-scott commented on src/main/java/com/giwankim/http/HttpSession.java
> +  void invalidate() {
여기에만 접근 제어자가 빠져 있는 이유가 궁금합니다.

2024-03-23 11:32 UTC, f-lab-scott commented on src/test/java/com/giwankim/http/HttpSessionsTest.java
> +    String id = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX";
매 케이스마다 직접 입력하시는 게 공수가 좀 소요될 것 같습니다.
[요런거](https://github.com/DiUS/java-faker) 활용해 보시는 건 어떨지요

2024-03-24 02:20 UTC, giwankim commented on src/test/java/com/giwankim/http/HttpSessionsTest.java
> +    String id = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX";
감사합니다. 사실 더 나아가서 fixture 정리하는 것에도 예전부터 의문점을 갖고 있었습니다. 패키지들이 많아지면 애매하게 비슷하면서 약간 다른 중복되는 fixture들이 생겼던 경험도 있고 여기저기 builder 만들어 놓고 케바케 테스트 케이스마다 만드는 것도 나쁘지는 않은 것 같은데요. 예를 들어 controller 테스트를 작성하려면 서비스 클래스 로직과 인증 로직이 엉켜 있어서 HttpRequest를 원하는 테스트 케이스에 맞게 조립해야할 것 같습니다. (우선은 책 진도 빼는 것을 션택하기는 했습니다.)

2024-03-24 06:12 UTC, giwankim commented on src/main/java/com/giwankim/http/HttpCookies.java
> +  HttpCookies(Map<String, String> cookies) {
인증 용도의 쿠키 사용은 대략적으로는 알고 있었으나 주로 jwt를 사용해 와서 알아볼 더 구체적으로 학습할 기회가 많지 않았습니다. 덕분에 MDN docs에 있는 쿠키 세팅 옵션들을 학습해 보았습니다. 저는 세션 용도로만 쿠키를 사용해 보았는데 쿠키로 그 사람의 브라우저 history나 사용자 프로파일을 만들 수 있다고 하는데 어떻게 하는지 궁금해지는군요.

2024-03-24 06:48 UTC, giwankim commented on src/main/java/com/giwankim/http/HttpSession.java
> +  private final String id;
우선 id는 보안과 관련 있으니 secure한 난수 생성 알고리즘을 사용해서 생성되면 좋을 것 같고 하나의 서블릿 보다는 이들의 전체 라이프사이클을 관리하는 컨테이너에서 관리하는 것이 맞을 것 같습니다. 응답/요청을 다루는 서블릿의 역활과는 별개이며 모든 서블릿들의 공통적인 횡단 관심사인 것 같기 때문입니다.

Tomcat의 소스 코드를 보니까 org.apache.catalina.util.SessionConfig라는 클래스에 ` private static final String DEFAULT_SESSION_COOKIE_NAME = "JSESSIONID";`라는 변수가 있고 세션 id를 만드는 클래스로는 org.apache.catalina.SessionIdGenerator라는 인터페이스와 StandardSessionIdGenerator라는 구현체가 있습니다.

제 추측에 사용자의 HTTP 요청이 들어오면 Tomcat은 이를 처리할 쓰레드와 HttpServletRequest의 구현체를 생성하는 과정에서 session id를 만들고 default로는 인메모리에 저장할 것 같습니다. (그렇다면 session 만료 및 gc는?)

2024-03-24 07:29 UTC, giwankim commented on src/main/java/com/giwankim/http/HttpSession.java
> +  void invalidate() {
실수인 것 같습니다. HttpRequest와 HttpResponse를 제외하고는 될 수 있으면 모든 클래스를 package-private으로 구현하려고 하는데 HttpSession은 controller 패키지에서 직접 사용하는 클래스이니 퍼블릭 메소드로 하는 것이 맞는 것 같습니다. 사실 이것도 코드 스멜인지 모르겠습니다. 지금은 서비스 레이어 구분 없이 서블릿에서 모든 것을 처리하고 있으나 이런 HTTP 통신에 관련된 모들 클래스들은 하나의 package 안에 넣는 것도 괜찮지 않을까 생각해 봅니다.

2024-03-25 10:56 UTC, f-lab-scott commented on src/main/java/com/giwankim/http/HttpCookies.java
> +  HttpCookies(Map<String, String> cookies) {
거창한 건 아니고, 쿠키에 히스토리 식별 키나 프로파일 식별 키를 심으면 되지 않을까요?
쿠키는 expiry를 자유롭게 부여할 수 있으니까, 세션 ID처럼 인메모리-짧은 유효기간을 두지 말고, DB 같은 매체에 긴 시간동안 저장하면, 그렇게 어려운 일은 아닐 것 같긴 합니다만..

2024-07-07 22:01 UTC, merged